/**
 * Demo 自定义页面 ID，对标 Android dokit 包下的 Class 简单类名
 */
export class DemoKitPageIds {
  /** 对标 Android DemoDoKitView */
  static readonly DEMO_DO_KIT_VIEW: string = 'DemoDoKitView';
  /** 对标 Android TestSimpleDoKitFloatView */
  static readonly TEST_SIMPLE_DOKIT_FLOAT_VIEW: string = 'TestSimpleDoKitFloatView';
  /** 对标 Android CustomDokitFragment */
  static readonly CUSTOM_DOKIT_FRAGMENT: string = 'CustomDokitFragment';
}
