/**
 * Activity/Fragment 传参 Key，对标 Android constant/BundleKey
 */
export class BundleKey {
  static readonly FILE_KEY: string = 'file_key';
  static readonly DIR_KEY: string = 'dir_key';
  static readonly FRAGMENT_INDEX: string = 'fragment_index';
  static readonly CUSTOM_FRAGMENT_CLASS: string = 'custom_fragment_class';
  static readonly SYSTEM_FRAGMENT_CLASS: string = 'system_fragment_class';
  static readonly ACCESSIBILITY_DATA: string = 'accessibility_data';
  static readonly PERFORMANCE_TYPE: string = 'performance_type';
  static readonly KEY_URL: string = 'key_url';
}
