source 'git@github.com:CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'DoKitSwiftDemo' do
  pod 'DoraemonKit', :subspecs => ['Core'],  :path => '../../../', :configurations => ['Debug']
end
