source 'git@github.com:CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'DoKitSwiftDemo' do
  pod 'AFNetworking'
  pod 'DoraemonKit-Swift', :path => '../../../', :configurations => ['Debug']
end
