platform:ios,’9.0’

#use_frameworks!
#inhibit_all_warnings! #消除第三方仓库的警告
# 新版本采用trunk模式，无需clone庞大的master
#source 'https://github.com/CocoaPods/Specs.git'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
    end
  end
end

#install! 'cocoapods', generate_multiple_pod_projects: true

target :'DoraemonKitDemo' do
  #pod 'WeexSDK', :git => 'git@github.com:apache/incubator-weex.git', :tag => '0.26.0'
  #pod 'DoraemonKit', :subspecs => ['Core','WithLogger','WithGPS','WithLoad','WithWeex', 'WithDatabase', 'WithMLeaksFinder'],  :path => '../../'
  #pod 'DoraemonKit', :subspecs => ['Core'],  :path => '../../'
  pod 'DoraemonKit', :subspecs => ['Core','WithLogger','WithGPS','WithLoad','WithDatabase', 'WithMLeaksFinder','WithWeex'], :path => '../../'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'SocketRocket', '~> 0.5'
  pod 'SDWebImageWebPCoder'
  pod 'FBRetainCycleDetector', :git => 'https://github.com/facebook/FBRetainCycleDetector.git'
  #pod 'fishhook', :git => 'git@github.com:facebook/fishhook.git', :configurations => ['Debug']
  pod 'YYDebugDatabase', :git => 'https://github.com/y500/YYDebugDatabase.git'
  #pod 'YYDebugDatabase', '2.'
end
