platform:ios,’8.0’
#use_frameworks!
#inhibit_all_warnings! #消除第三方仓库的警告
source 'git@github.com:CocoaPods/Specs.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
        end
    end
end

#install! 'cocoapods', generate_multiple_pod_projects: true

target :'DoraemonKitDemo' do
  #pod 'DoraemonKit', :subspecs => ['Core','WithLogger','WithGPS','WithLoad','WithWeex', 'WithDatabase', 'WithMLeaksFinder'],  :path => '../../'
  #pod 'DoraemonKit', :subspecs => ['Core'],  :path => '../../'
  pod 'DoraemonKit', :subspecs => ['Core','WithGPS','WithGPS', 'WithMLeaksFinder', 'WithDatabase'], :path => '../../'
  pod 'AFNetworking','2.6.3'
  pod 'SDWebImage', '5.0.6'
  pod 'FBRetainCycleDetector', :git => 'git@github.com:facebook/FBRetainCycleDetector.git', :configurations => ['Debug']
  #pod 'FBRetainCycleDetector'
end
